#!/bin/bash

if [ ! -x "`which docker`" ]; then
	echo "This test environment requires docker"
	exit 1
fi

# Start the test server
if [ "$1" != "" ]; then
	nautpath=$1
else
	nautpath=`pwd`
fi

# Kill existing machines
for machine in uat1 prod1 deploynaut; do
	if [ "`docker ps -a | grep $machine`" != "" ]; then
		echo "Shutting down old $machine..."
		docker rm -f $machine
	fi
done

echo "Starting uat1..." && \
docker run --name uat1 -dP -p 3001:80 -p :22  sminnee/deploynaut-test-webserver && \
echo "Starting prod1..." && \
docker run --name prod1 -dP -p 3002:80 -p :22 sminnee/deploynaut-test-webserver && \
echo "Starting deploynaut..." && \
docker run --name deploynaut -dP -p 3000:80 --link uat1:env_standard_uat1 --link prod1:env_standard_prod1 -v $nautpath:/var/www/html sminnee/deploynaut-test-server && \

echo "Test environment started

 - Visit http://localhost:3000/ to access Deploynaut
 - Visit http://localhost:3001/ to acces a UAT site to deploy to
 - Visit http://localhost:3002/ to acces a Live site to deploy to"